# Generated by Django 3.1.6 on 2021-02-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('location', models.CharField(max_length=50, verbose_name='Город')),
                ('logo', models.ImageField(upload_to='images/%Y/%d/%m/', verbose_name='Лого')),
                ('description', models.TextField(max_length=2000, verbose_name='Информация')),
                ('employee_count', models.PositiveSmallIntegerField(verbose_name='Кол-во сотрудников')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Код')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/%Y/%d/%m/', verbose_name='зображение')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('skills', models.CharField(max_length=150, verbose_name='Навыки')),
                ('salary_min', models.PositiveSmallIntegerField(verbose_name='Мин зарплата')),
                ('salary_max', models.PositiveSmallIntegerField(verbose_name='Макс зарплата')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                              to='company.company')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                                 to='company.speciality')),
            ],
        ),
    ]
