# Generated by Django 3.1.6 on 2021-02-06 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published',
            field=models.DateTimeField(
                default=datetime.datetime(2021, 2, 6, 17, 17, 23, 653662),
                verbose_name='Опубликовано'
            ),
        ),
    ]
